In [1]:
import numpy as np

In [94]:
#Define tensor product of n simar gates, we need this function for hadmard product
def Hadmard_product(A, n):
    result = np.array([[1]])
    for i in range(n):
        result = np.kron(result, A)
    return result

In [96]:
#Sanity check, verifying hadmard to 2 gates
A = (1 / np.sqrt(2)) *np.array([[1, 1], [1, -1]])
result = Hadmard_product(A, 2)
print(result)

[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


In [97]:
#This will make oracle matrix, given n state and kth target
def make_oracle(n, k):
    I = np.identity(2**n)
    v = np.zeros(2**n)
    v[k] = 1
    return 2 * np.outer(v, v) - I

In [59]:
#Check, 3 state will give 2**3 dimention matrix 
result = make_oracle(3, 1)
print(result)

[[-1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]


In [98]:
#convert a given number of state, with kth target. Make N vectors accordingle
def write_vectors(n,k):
    vectors =np.array([np.array([1,0]) for i in range(n)])
    vectors[k] = np.array([0,1])
    return vectors

In [100]:
#a 5 state system with 2nd target 
V=write_vectors(5,2)
V

array([[1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0]])

In [101]:
# State needs to be tensor product before we can use matrix product
def tensor_product(vectors):
    result = np.array([1])
    for v in vectors:
        result = np.kron(result, v)
    return result

In [103]:
#This is a tensor product state
tensor_product(V)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
#Grovers algorith
#1) Apply hadmard to all states
#2) Apply orakle, then diffuser then hadmard
#3) Apply second step int(np.pi * np.sqrt(2**N) / 4) times


def grover(N, target):
    
    
    # Define the Hadamard matrix
    H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]], dtype=complex)

    
    # Initialize the quantum state
    V = write_vectors(N,target)
    state = tensor_product(V)
    initial_state = tensor_product(V)
    

    # Define the Hadamard_tensor gate   
    H_tensor = Hadmard_product(H, N)   


    # Define the oracle tensor that marks the target state
    oracle_tensor=make_oracle(N, target)
    
    
    # Define the diffusion operation
    # ? need to add here
    
    
    #first hadmard opretaion before sending to iterator
    state = np.dot(H_tensor, state)

    # Apply the oracle and diffusion operators(in ineration)
    for i in range(int(np.pi * np.sqrt(2**N) / 4)):
        
        
        #Apply orackle here
        state = np.dot(oracle_tensor,state)
    
        
        # Apply the Hadamard gate to all qubits
        state = np.dot(H_tensor, state)
        
        
        #Diffuser operator comes here    
        #?
        
        
        #hadmard to all
        #state = np.dot(H_tensor, state)

    # Measure the qubits
    prob = np.abs(state[target])**2

    return state #V, initial_state , prob
#This will give abserd result as diffuser operator is not defined, But try switching output to state, V,
#initial state and prob to get sense of intermediate results.

In [110]:
grover(13,2)

array([ 3.66353722e-05+0.j,  3.66353722e-05+0.j,  7.89158981e-03+0.j, ...,
        3.66353722e-05+0.j, -3.66353722e-05+0.j, -3.66353722e-05+0.j])

In [106]:
grover(5,2)

array([ 0.19611165+0.j,  0.19611165+0.j,  0.11324757+0.j,  0.15744174+0.j,
       -0.15744174+0.j, -0.15744174+0.j, -0.19611165+0.j, -0.19611165+0.j,
        0.19611165+0.j,  0.19611165+0.j,  0.15744174+0.j,  0.15744174+0.j,
       -0.15744174+0.j, -0.15744174+0.j, -0.19611165+0.j, -0.19611165+0.j,
        0.19611165+0.j,  0.19611165+0.j,  0.15744174+0.j,  0.15744174+0.j,
       -0.15744174+0.j, -0.15744174+0.j, -0.19611165+0.j, -0.19611165+0.j,
        0.19611165+0.j,  0.19611165+0.j,  0.15744174+0.j,  0.15744174+0.j,
       -0.15744174+0.j, -0.15744174+0.j, -0.19611165+0.j, -0.19611165+0.j])